### PR TITLE
Added Functionality For API Call By Query Params In URL for GET

### PR DESCRIPTION
**Pull request by azharakbar**
Now You Can Query By
curl -X GET "http://localhost:8000/api/users?property=value"

Signed-off-by: Mohammed Azhar <azharakbar@gmail.com>

### CODE REVIEW

**Comment by azharakbar** [comment]
@adrianobrito I have raised the PR ... pls check it .. :)

**Comment by azharakbar** [comment]
@adrianobrito In order for the build to pass .. test cases has to be changeed ... :)

**Comment by azharakbar** [comment]
@adrianobrito ....Hi .. I am working on this issue ... pls neglect the above PR .. .
I jst need one more clarification...
Like ... Do we need both type of querying or is it like we can completely avoid .. `/api/users/123` form and only allow users to query in the form `/api/collection?property=value` 
I prefer that `/api/users/123` should be removed ... 
What is ur decision ??

**Comment by adrianobrito** [comment]
> Like ... Do we need both type of querying or is it like we can completely avoid .. /api/users/123 form and only allow users to query in the form /api/collection?property=value

I think we should keep `/api/users/123` because it's something related with [RESTful archictecture ](https://en.wikipedia.org/wiki/Representational_state_transfer#Applied_to_Web_services) and the server aims to be a tool that mock RESTful web services. The `/api/collection?property=value` is a way of extract a subcollection that matches with some query criteria specied in query string.  The `/api/users/123` form is a way to get an individual JSON object that has 123 as id, instead a subcollection like it should have to be in a HTTP GET that has some criteria in query string. 

P.S: I checked the file changes you did in this pull request and I checked that you just add the implementation code in the already existent implementations. In the issue, I warn about create a new component and compose the server with this in order to keep uncoupled code. If is possible to you, we can have a little talk or something to help you in this journey.


Thank you, after all
😃

**Comment by azharakbar** [comment]
@adrianobrito  Hi ,
Yea ... I got it ... so we need both implementations ... 
I jst nw completed the test suite and implementation for  onlu /api/collexn?prop=value type .. completely avoiding the existing form .. now will integrate both into one .. .

But, i didnt understand what u meant by creating a new component ?? 

Ofcourse, we can talk on this ... 

Thanx...

**Pull request closed without merging**
